// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by ApolloApi.
NSObject<FlutterMessageCodec> *ApolloApiGetCodec(void);

@protocol ApolloApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)introductionWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)greetingWho:(NSString *)who error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ApolloApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ApolloApi> *_Nullable api);

NS_ASSUME_NONNULL_END
