// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "ApolloApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[ error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null] ];
  }
  return @[ result ?: [NSNull null]  ];
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



NSObject<FlutterMessageCodec> *ApolloApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void ApolloApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ApolloApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ApolloApi.introduction"
        binaryMessenger:binaryMessenger
        codec:ApolloApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(introductionWithError:)], @"ApolloApi api (%@) doesn't respond to @selector(introductionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api introductionWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ApolloApi.greeting"
        binaryMessenger:binaryMessenger
        codec:ApolloApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(greetingWho:error:)], @"ApolloApi api (%@) doesn't respond to @selector(greetingWho:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_who = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api greetingWho:arg_who error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
